fix race condition in Reader due to concurrent map write
```
fatal error: concurrent map writes
github.com/richardlehane/msoleps.addDefaults(...)
	/go/pkg/mod/github.com/richardlehane/msoleps@v1.0.3/sets.go:20
github.com/richardlehane/msoleps.(*Reader).start(0xc001bb1f78, {0xc8a180?, 0xc00037be80?})
	/go/pkg/mod/github.com/richardlehane/msoleps@v1.0.3/msoleps.go:125 +0x2de
github.com/richardlehane/msoleps.(*Reader).Reset(...)
	/go/pkg/mod/github.com/richardlehane/msoleps@v1.0.3/msoleps.go:76
...
```